### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by IsThatTheRealNick** [FlashyReese/CommandAliases#10]
{
		"commandMode": "COMMAND_CUSTOM",
		"customCommand": {
			"parent": "testconvert",
			"type": "literal",
			"actions": [
				{
					"command": "execute if entity @p[nbt={Inventory:[{id:"minecraft:emerald",Count:2b}]}] run clear $executor_name() minecraft:diamond 1",
					"commandType": "SERVER"
				}
			],
			"message": "Exchanged 2 Emeralds for 1 Diamond!"
		}
	}
Fails to reload, error within the "command" line unterminated object between the 'n' and 'v' in 'Inventory'

**Comment by FlashyReese** [comment]
Your JSON formatting is invalid. You need to escape your quotes in JSON string fields like so `\"`
```json
{
	"commandMode": "COMMAND_CUSTOM",
	"customCommand": {
		"parent": "testconvert",
		"type": "literal",
		"actions": [
			{
				"command": "execute if entity @p[nbt={Inventory:[{id:\"minecraft:emerald\",Count:2b}]}] run clear $executor_name() minecraft:diamond 1",
				"commandType": "SERVER"
			}
		],
		"message": "Exchanged 2 Emeralds for 1 Diamond!"
	}
}
```

**Comment by IsThatTheRealNick** [comment]
Ohhh, thank you :) so then what about like this (sorry, not the smartest)
{
		"commandMode": "COMMAND_CUSTOM",
		"customCommand": {
			"parent": "clearlag",
			"type": "literal",
			"actions": [
				{
					"command": "tellraw @p ["",{"text":"[ClearLag] ","bold":true,"color":"#FF0800"},{"text":"Clearing Ground Items In ","bold":true,"italic":true,"color":"aqua"}]",
					"commandType": "SERVER"					
				},
			],
			"message": ""
		}
	},

**Comment by FlashyReese** [comment]
I would recommend looking up a tutorial on how JSON works, you can also get a text editor with JSON formatting support.
```json
{
	"commandMode": "COMMAND_CUSTOM",
	"customCommand": {
		"parent": "clearlag",
		"type": "literal",
		"actions": [
			{
				"command": "tellraw @p [\"\",{\"text\":\"[ClearLag] \",\"bold\":true,\"color\":\"#FF0800\"},{\"text\":\"Clearing Ground Items In \",\"bold\":true,\"italic\":true,\"color\":\"aqua\"}]",
				"commandType": "SERVER"
			}
		],
		"message": ""
	}
}
```

**Comment by IsThatTheRealNick** [comment]
Yea, thank you but um sorry 1 more thing,
{
		"commandMode": "COMMAND_CUSTOM",
		"customCommand": {
			"parent": "convert",
			"type": "literal",
			"actions": [
				{
					"command": "give $executor_name() minecraft:diamond",
					"commandType": "SERVER"
				}
			],
			"message": ""
		}
	}
	that give command works, but then drops an invisible diamond(sometimes visible) on the ground granting the player with 2 diamonds. Even if I specify at the end 'diamond 1' it will give one to the player and drop an invisible one on the ground  :/

**Comment by FlashyReese** [comment]
It don't seem to have the problem you are mentioning, make sure you don't have any duplicated commands with the same name.

**Comment by IsThatTheRealNick** [comment]
I can and did rename it + I've removed all other commands and it will still drop an extra for no reason :/ Run the command again, leave the server and rejoin and you might see a diamond sitting in front of you as well as in your inventory. Because when I run it, I get one in my inventory and it basically 'drops' another one/extra from my character

**Comment by FlashyReese** [comment]
That is interesting, is it always 2 drops? Can you provide a list of mods you are running?

**Comment by IsThatTheRealNick** [comment]
Yes, it's always 2 drops.
Im running a lot of mods-
![image](https://user-images.githubusercontent.com/17803080/108466258-5a6de100-7251-11eb-9e6d-8d7948f41fba.png)
Few more like vanish, vein excavator, worldeditcui and worldedit

**Comment by FlashyReese** [comment]
I really can't seem to replicate the issue you mentioned on both client or server. Can you test command aliases on it's own? Also can you provide me your JSON file?
