### ISSUE TITLE
{arg::player#player} throws error

### ISSUE THREAD

**Issue by TheRobified** [FlashyReese/CommandAliases#11]
**Error:** Command Aliases/ERROR No method found for "{arg::player#player}"

Did syntax change? I tried having a look at the wiki, but I don't see any changes.

This is on 0.4.2. Issue wasn't present in 0.4.1 (which I've reverted to for now).

**Comment by amnotbananaama** [comment]
Can you post your the full JSON for your command?

**Comment by FlashyReese** [comment]
I did rename it to match the wiki it should be `{arg::minecraft:player#player}` now. See https://github.com/FlashyReese/CommandAliases/blob/4b88d53fac09e1c21f2f8c1a88725c30938f6619/src/main/java/me/flashyreese/mods/commandaliases/classtool/impl/argument/ArgumentTypeManager.java#L53-L100

**Comment by TheRobified** [comment]
Fixed. Yeah, when I was looking through the wiki, it was still referencing just {arg::player#player}. Looks to be updated now, and with the updates I made, it's all working now. Resolved! :)

Thanks for the help.

**Comment by FlashyReese** [comment]
This was my bad, I completely forgot about it, but all argument types now work including NBT tags.
