### ISSUE TITLE
Bugs and Question

### ISSUE THREAD

**Issue by barraIhsan** [FlashyReese/CommandAliases#13]
Bugs, try clear all you inventory, and run `/clear`
```
{
		"commandMode": "COMMAND_REASSIGN_AND_ALIAS",
		"command": "clear",
		"reassignTo": "minecraft:clear",
		"execution": [
			{
				"command": "minecraft:clear",
				"type": "CLIENT"
			},
			{
				"command": "replaceitem entity @s hotbar.0 minecraft:wooden_sword",
				"type": "CLIENT"
			}
		]
	}
```
Then, the second command doesn't run if the previous command doesn't success. But if the command success it will run the second command.
Question
1. Can you turn off the send command feedback just for `commandAliases`?
![image](https://user-images.githubusercontent.com/57800056/112262169-c9e74e00-8c9f-11eb-94b8-624b35c48dd9.png)
2. Is this client side, if no, is the `"type": "CLIENT"` is client. Because I see no reason why the `"type": "CLIENT"` is not client. Because we can run `/clear` and `/replaceitem entity @s hotbar.0 minecraft:wooden_sword` if we are op

**Comment by FlashyReese** [comment]
Nice catch, apparently Minecraft throws an error internally if your inventory is empty and you run the `clear` command. I have fixed this in https://github.com/FlashyReese/CommandAliases/commit/1208fd1bca6d0db346ddf73920e2e8ade0363818, you can try this [GitHub Actions](https://github.com/FlashyReese/CommandAliases/runs/2183879513) build for the meanwhile, just click and download `build-artifacts`.

1. Command feedback only occurs if the user is OP, I will have an option in the future to turn this off for OPs as well.
2. When you define `"type": "CLIENT"`, the player tries to execute the command. Defining it as `"type": "SERVER"`, the server will try to execute the command(it is like the console and it will try to run the command).

If this command is meant for OP only then it should be define as `"type": "CLIENT"`.

Also you should use `COMMAND_REASSIGN_AND_CUSTOM`, although this isn't updated in the wiki, it works on the latest release.
```json5
  {
    "commandMode": "COMMAND_REASSIGN_AND_CUSTOM",
    "command": "clear", //This line will not be necessary in the next release.
    "reassignTo": "minecraft:clear",
    "customCommand": {
      "parent": "clear",
      "type": "literal",
      "permission": 1, //Only for OPs
      "actions": [
        {
          "command": "minecraft:clear",
          "commandType": "CLIENT"
        },
        {
          "command": "replaceitem entity @s hotbar.0 minecraft:wooden_sword",
          "commandType": "CLIENT"
        }
      ]
    }
  }
```

I will leave my [Discord server](https://discord.gg/uGPuy7JydZ) here(it's work in progress), if you have any issues/questions feel free to ask me there.

**Comment by barraIhsan** [comment]
```
When you define "type": "CLIENT", the player tries to execute the command. Defining it as "type": "SERVER", the server will try to execute the command(it is like the console and it will try to run the command).
```
So its mean we can run it in any server as long we have the permission. For example anyone can run `/trigger` so its mean that I can enter the commandAliases for `/trigger` at any server?

**Comment by FlashyReese** [comment]
> So its mean we can run it in any server as long we have the permission. For example anyone can run `/trigger` so its mean that I can enter the commandAliases for `/trigger` at any server?

Well no, Command Aliases is server sided(internal server/dedicated server), if you use Command Aliases on your client, it only works on your single player worlds. The dev branch does support client sided commands, but it's heavily work in progress as well.

**Comment by barraIhsan** [comment]
oh ok
