### ISSUE TITLE
[Question] Test or go on

### ISSUE THREAD

**Issue by dts77** [FlashyReese/CommandAliases#15]
[commandaliases.txt](https://github.com/FlashyReese/CommandAliases/files/6369134/commandaliases.txt)
Hello,
First thanks for this mod, it's a greate job ;)

As you can see in joined file , I created sub commands to my daughter to enchant her stuff.
But if an enchant is already on it stop and do not go on.
I sthere a way to test if it's already have the enchant or to gon on ?

Thanks for your help

**Comment by FlashyReese** [comment]
First of all thank you very much.

Sadly not yet, but I've have a got a features that might work but it's still in the development branch. 

I will look into this, this weekend :P

**Comment by dts77** [comment]
Thanks for your quick reply :D

**Comment by FlashyReese** [comment]
If that's the only custom command you have for the moment you can try this [development build](https://github.com/FlashyReese/CommandAliases/suites/2333092537/artifacts/49173848). The format is identical although I spotted some errors in your JSON, just some message parameters.
[commandaliases.txt](https://github.com/FlashyReese/CommandAliases/files/6371008/commandaliases.txt)
