### ISSUE TITLE
/tellraw won't work with CommandAliases

### ISSUE THREAD

**Issue by ghost** [FlashyReese/CommandAliases#16]
My plan was to have a tellraw run as  a SERVER command so that all players can use it with a simple command.
But the JSON file stops that as the command in question`(tellraw @a [{"text":"Click here for ","color":"yellow"},{"text":"BlueMap","bold":true,"color":"dark_blue","clickEvent":{"action":"open_url","value":"https://rotf.lol/farmtasticraftsbluemap/"}},{"text":" Click here for","bold":true,"color":"yellow"},{"text":" ","bold":true,"color":"dark_blue"},{"text":"Dynmap","bold":true,"color":"aqua","clickEvent":{"action":"open_url","value":"https://rotf.lol/farmtasticraftsdynmap/"}}])` also uses JSON text components. Would there be a workaround for this?

**Comment by FlashyReese** [comment]
You need to escape the JSON itself when placing it as a string. If you can upload the entire command alias JSON file I can help you out.

Edit:
It should look like this instead `tellraw @a [{\"text\":\"Click here for \",\"color\":\"yellow\"},{\"text\":\"BlueMap\",\"bold\":true,\"color\":\"dark_blue\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https:\/\/rotf.lol\/farmtasticraftsbluemap\/\"}},{\"text\":\" Click here for\",\"bold\":true,\"color\":\"yellow\"},{\"text\":\" \",\"bold\":true,\"color\":\"dark_blue\"},{\"text\":\"Dynmap\",\"bold\":true,\"color\":\"aqua\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https:\/\/rotf.lol\/farmtasticraftsdynmap\/\"}}]`

**Comment by ghost** [comment]
Thanks.
That looks complicated though and I plan on adding a lot of tellraws.
Please can you explain what I do to the tellraws as well as the edited one you sent?
Thanks for the help though!
Currently this is my JSON file
[GitHub doesn't support uploading of JSON files, so I have shared it on Google Drive](https://drive.google.com/file/d/15LkRP1uOLWJJta9GCMgV9s0Ax_FL4A9H/view?usp=sharing)

**Comment by ghost** [comment]
Also, it may already be there and I missed it, but maybe this should be added to the wiki?

**Comment by FlashyReese** [comment]
> Thanks.
> That looks complicated though and I plan on adding a lot of tellraws.
> Please can you explain what I do to the tellraws as well as the edited one you sent?
> Thanks for the help though!
> Currently this is my JSON file
> [GitHub doesn't support uploading of JSON files, so I have shared it on Google Drive](https://drive.google.com/file/d/15LkRP1uOLWJJta9GCMgV9s0Ax_FL4A9H/view?usp=sharing)

Use an escape tool like https://www.freeformatter.com/json-escape.html, I will update the wiki when I have time, I'm quite busy with university.
