### ISSUE TITLE
Error while executing command

### ISSUE THREAD

**Issue by Soham52** [FlashyReese/CommandAliases#19]
this is the code:
[
{
	"commandMode": "COMMAND_ALIAS",
	"command": "cords",
	"execution": [
		{
			"command": "execute at {this::SELF} run trigger ch_toggle",
			"type": "CLIENT"
		}
	]
}
]
after reloading in-game when typing /cords as a OP it works but when doing the same as a non OP player this error comes
![image](https://user-images.githubusercontent.com/73898737/126624555-2fbcd508-a769-42f4-bdab-428dc8322c1c.png)

**Comment by FlashyReese** [comment]
Use type as SERVER for the non OP user issue. As for the other issue that will be fixed next release.
