### ISSUE TITLE
[Request] Optional Parameteres

### ISSUE THREAD

**Issue by supersaiyansubtlety** [FlashyReese/CommandAliases#2]
I know you say "All arguments are required, you can't create optional argument yet, " implying you have plans for optional parameters; 
I'm just letting you know you have at least one user that would find this feature useful : ]

**Comment by FlashyReese** [comment]
Thank you very much, yes it is planned but I haven't gotten around to it.

**Comment by FlashyReese** [comment]
I have started working on it, it's currently on a separate branch since I'm unsure if it breaks anything or is broken. Here is a prebuilt from GitHub Actions if you are interested https://github.com/FlashyReese/CommandAliases/actions/runs/371680335 

```json
[
  {
      "command": "newgive {arg::entity#player} {arg::item_stack#item} [arg::brigadier:integer#count]",
      "execution" : [
        {
          "command": "give {player} {item} [count]",
          "type": "SERVER",
          "sleep": "1000"
        }
      ]
    },
    {
      "command": "foo {arg::brigadier:bool#bool} [arg::player#message@jsonString]",
      "execution": [
        {
          "command": "tellraw @a {\"text\":\" {bool} [message]\"}",
          "type": "CLIENT",
          "message": "with bool"
        }
      ]
    }
]
```
Here are some examples I used

Edit: If you run into any issues please kindly report it here, I would appreciate it :D

**Comment by FlashyReese** [comment]
Update: I have patched bug when using multiple optional arguments. See [50e41f1](https://github.com/FlashyReese/CommandAliases/actions/runs/373352868)

Another working example
```json
[
    {
      "command": "foo {arg::brigadier:bool#bool} [arg::player#player@jsonString] [arg::greedy_string#message@jsonString]",
      "execution": [
        {
          "command": "tellraw @a {\"text\":\" {bool} [message] [player]\"}",
          "type": "CLIENT"
        }
      ]
    }
]
```
