### ISSUE TITLE
Command redirect did not work

### ISSUE THREAD

**Issue by Pixaurora** [FlashyReese/CommandAliases#26]
There's no error, but the below format does not do anything. I also found that reversing the placement of "say" and "s" also did nothing, so it doesn't seem to just be me putting stuff in the wrong place. Was the format updated since the latest wiki page was made?
```json
{
    "commandMode": "COMMAND_REDIRECT",
    "redirectCommand": {
        "command": "say",
        "redirectTo": "s"
    }
}
```

**Comment by FlashyReese** [comment]
I assume you are using the version `0.6.0`, it's a bug with my implementation to work with LuckPerms. You can downgrade to `0.5.0` or install LuckPerms and grant yourself permission of `commandaliases.s`.

The command should look like this 
```json
{
    "commandMode": "COMMAND_REDIRECT",
    "redirectCommand": {
        "command": "s",
        "redirectTo": "say"
    }
}
```
