### ISSUE TITLE
CommandMode COMMAND_REDIRECT_NOARG will not work with numbers

### ISSUE THREAD

**Issue by bluprintLFT** [FlashyReese/CommandAliases#33]
If I put any number in the redirectTo field, the command will not show up ingame.

Example:
{
                "commandMode": "COMMAND_REDIRECT_NOARG",
                "redirectCommand": {
                        "command": "day",
                        "redirectTo": "time set day"
                        }
        }
will work.

{
                "commandMode": "COMMAND_REDIRECT_NOARG",
                "redirectCommand": {
                        "command": "day",
                        "redirectTo": "time set 0"
                        }
        }
will NOT work.

**Comment by FlashyReese** [comment]
As mentioned in the wiki it does not work with arguments. 

What want you to do is achievable by using custom commands
```json
{
	"commandMode": "COMMAND_CUSTOM",
	"customCommand": {
		"parent": "day"
		"actions": [
			{
				"command": "time set 0",
				"commandType": "SERVER"
			}
		]
	}
}
```
