### ISSUE TITLE
Failure to register aliases for mod-added commands on startup.

### ISSUE THREAD

**Issue by John-Paul-R** [FlashyReese/CommandAliases#34]
(I believe) Due to [this command registration change](https://github.com/FlashyReese/CommandAliases/commit/dc14456f5b550f471dbed6701d2ed5689949d3b4#diff-58f71e936b4f5552a45034ccd68014db4476cb368a98fbc0d6b913e949f22b49R67-R74), it is now possible for CommandAliases to load aliases before other mods have registered their commands, which will cause the registration process to fail for any CommandAliases nodes that reference one of these not-yet-registered commands.

Repro:

- Add [EssentialCommands](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.26.3-mc1.19)
- Add [CommandAliases](https://github.com/FlashyReese/CommandAliases/releases/tag/mc1.19-0.9.3)
- Add this config to `config/commandaliases/`

```
{
  "commandMode": "COMMAND_REDIRECT",
  "redirectCommand": {
    "command": "h",
    "redirectTo": "essentialcommands home tp"
  }
}
```

- Observe the following logged error (and that `/h` does not exist:

```
[SERVER] COMMAND_REDIRECT - Could not find existing command "essentialcommands home tp".
```

- additionally, note that after executing `/commandaliases reload`, `/h` is registered and works as intended.

**Comment by FlashyReese** [comment]
The registration callback is earlier for Command Aliases because of the mod id I presume. If I revert back this breaks all commands when using `/reload` for datapacks.

I'm not sure how to tackle this issue, if someone knows a way to get around this without having both issues appear feel free to PR.

**Comment by John-Paul-R** [comment]
Alright, I've put up a PR with a possibly way to resolve this. Not sure I particularly _like_ the approach, but I think it should work. Still need to do some local testing. (#35)
