### ISSUE TITLE
Mod loads aliases too early

### ISSUE THREAD

**Issue by Awakened-Redstone** [FlashyReese/CommandAliases#36]
The mod loads the aliases before all mod commands are registered, resulting on it failing to apply the alias during `/reload` or server startup
![image](https://user-images.githubusercontent.com/40528665/202869340-935ea858-687a-46e3-939c-11a7e777f774.png)

**Comment by FlashyReese** [comment]
This issue has been fixed on the development branch, I just need to find time to release an update but it involves me rewriting the wiki due to a format change. For the meanwhile you can just workaround this by calling `/commandaliases reload`.

**Comment by Awakened-Redstone** [comment]
I have noticed that it didn't happen on the last server start I did. Well,  ¯\_(ツ)_/¯

**Comment by FlashyReese** [comment]
I released a hotfix with version `0.9.4`.

**Comment by Awakened-Redstone** [comment]
I did a debug and the only commands I have found loading after the mod were carpet and polymer ones, but they don't use the fabric event (instead they use a mixin) to register the commands so it seems to be all fine, thanks!

**Comment by FlashyReese** [comment]
Unfortunately, there is no way for me to deal with mods mixing into Minecraft commands instead. I am using the standard of Fabric API.
