### ISSUE TITLE
[SERVER] COMMAND_REDIRECT_NOARG - Could not find existing command "gamemode creative"

### ISSUE THREAD

**Issue by kraoc** [FlashyReese/CommandAliases#42]
- commandaliases-1.0.0+mc1.19.3-build.59.jar
- Fabric 1.19.3

**config/commandaliases/creatif.json**
> {
>     "schemaVersion": 1,
>     "commandMode":"COMMAND_REDIRECT_NOARG",
>     "command":"creatif",
>     "redirectTo":"gamemode creative"
> }

Same for:

- gamemode spectator
- gamemode survival
- gamemode creative
- gamemode adventure

**Comment by kraoc** [comment]
These are working anyway:

> {
>     "schemaVersion": 1,
>     "commandMode":"COMMAND_REDIRECT_NOARG",
>     "command":"difficile",
>     "redirectTo":"difficulty hard"
> }

> {
>     "schemaVersion": 1,
>     "commandMode":"COMMAND_REDIRECT_NOARG",
>     "command":"jour",
>     "redirectTo":"time set day"
> }

**Comment by FlashyReese** [comment]
I believe they changed gamemode argument in 1.19.3
You can try using custom commands like
```json
{
    "schemaVersion": 1,
    "commandMode": "COMMAND_CUSTOM",
    "command": "creatif",
    "actions": [
        {
            "command": "gamemode creative",
            "commandType": "CLIENT"
        }
    ]
}
```

**Comment by kraoc** [comment]
It works ! Thanks !
