### ISSUE TITLE
"gamemode survival" not working

### ISSUE THREAD

**Issue by Mailiax** [FlashyReese/CommandAliases#43]
[Server thread/ERROR]: [SERVER] COMMAND_REDIRECT_NOARG - Could not find existing command "gamemode survival"

Do you know why "gamemode survival" doesn't work but something like "weather clear" works? 

Alias is taken directly from the quick start guide:

`{
    "schemaVersion": 1,
    "commandMode": "COMMAND_REDIRECT_NOARG",
    "command": "survival",
    "redirectTo": "gamemode survival"
}`

Minecraft version is 1.19.3. Am I just missing something?

**Comment by FlashyReese** [comment]
1.19.3 had some `gamemode` argument changes, they now have an explicit argument type rather than a literal one. The only workaround is to use https://github.com/FlashyReese/CommandAliases/issues/42#issuecomment-1356108246. At least for 1.19.3

**Comment by Mailiax** [comment]
That works. Thank you.
