### ISSUE TITLE
trigger command not aliasing correctly

### ISSUE THREAD

**Issue by JadeNeoma** [FlashyReese/CommandAliases#45]
Trying to use this to turn /trigger status-live from a datpack into /status live. It doesn't throw an error but the command just does nothing. My suspicion is that the trigger command is not working as it can't find the player that used it. I'll leave the datapack and tyhe config files I'm using left below. The config includes other status commands I'm trying to get working, but focusing on live is my goal. 
[status-plugin-1-1.zip](https://github.com/FlashyReese/CommandAliases/files/10370595/status-plugin-1-1.zip)
`{
    "schemaVersion": 1,
    "commandMode": "COMMAND_CUSTOM",
    "command": "status",
    "permission": 0,
    "message": "hello parent command",
    "children": [
        {
        "child": "live",
        "type": "argument",
        "argumentType": "minecraft:word",
        "suggestionProvider": {
            "suggestionMode": "DATABASE_STARTS_WITH", 
            "suggestion": "$executor_name().home.suggestions"
        },
        "permission": 0,
        "actions": [
            {
                "command": "trigger Status-Live"
            }
        ]
        },
        {
            "child": "recording",
            "type": "argument",
            "argumentType": "minecraft:word",
            "permission": 0,
            "actions": [
                {
                    "command": "trigger Status-Recording"
                }
            ]
        },
        {
            "child": "reset",
            "type": "argument",
            "argumentType": "minecraft:word",
            "permission": 0,
            "actions": [
                {
                    "command": "trigger Status-Reset"
                }
            ]
        }
    ]
    }`

**Comment by JadeNeoma** [comment]
Okay, Fixed it. It was a nightmare though so I'm glad I added the issue. The commandType needed to be CLIENT

**Comment by FlashyReese** [comment]
You should remove the suggestion provider if you aren't using it
`"suggestionProvider": { "suggestionMode": "DATABASE_STARTS_WITH",  "suggestion": "$executor_name().home.suggestions" }`
