### ISSUE TITLE
Feature Request: Fabric PlaceholderAPI

### ISSUE THREAD

**Issue by manashard** [FlashyReese/CommandAliases#46]
Hello, Requesting This because would drastically increase the potential of the CommandAliases and other mods

An example usage:

Checking LuckPerms permission:
`commandaliases compare equals \"true\" \"%luckperms_check_permission%\"`
More in: https://luckperms.net/wiki/Placeholders and https://placeholders.pb4.eu/user/mod-placeholders/

Default placeholders from PlaceholderAPI(Fabric):
https://placeholders.pb4.eu/user/default-placeholders/

Some Fabric mods using PlaceholderAPI:
https://placeholders.pb4.eu/user/mod-placeholders/

Implementing PlaceholderAPI page:
https://placeholders.pb4.eu/dev/getting-started/

Thanks for your time and efforts to maintain this amazin mod
Cheers.

**Comment by FlashyReese** [comment]
Can you explain how the `%luckperms_check_permission%` placeholder works? I noticed that the LuckPerms documentation mentions a `<permission>` argument. Is this check done on the current command? Additionally, in what scenarios would using this placeholder be beneficial when compared to the current Command Aliases feature provided by LuckPerms, since custom commands already have permission tags assigned to them?

**Comment by FlashyReese** [comment]
Try this build, https://github.com/FlashyReese/CommandAliases/actions/runs/3916411312

**Comment by manashard** [comment]
> Can you explain how the `%luckperms_check_permission%` placeholder works? I noticed that the LuckPerms documentation mentions a `<permission>` argument. Is this check done on the current command? Additionally, in what scenarios would using this placeholder be beneficial when compared to the current Command Aliases feature provided by LuckPerms, since custom commands already have permission tags assigned to them?

Example usage:
`"command": "commandaliases compare equals \"true\" \"%luckperms:check_permission allowed%\""`

In this specific case will allow me to check if the player has the permission `allowed` in luckperms set to `true` and do actions based on true/false using `actionsIfSuccessful` and `actionsIfUnsuccessful`.
Basically will allow to compare any output coming from placeholders and execut actions based on them

> Try this build, https://github.com/FlashyReese/CommandAliases/actions/runs/3916411312

Yoo it works well but its limited only if the executor are a player(expected due the placeholders are only from players)

Is it possible to create a new function to check players permission direct from server something like:

`$get_permissioninfo_value({{player}}.allowed)`

Expected output will be `true/false` depending if the player has or no the specific permission on luckperms, will useful when the check needs to be done using`"commandType": "SERVER"`.

Thanks again

**Comment by FlashyReese** [comment]
> Is it possible to create a new function to check players permission direct from server something like: $get_permissioninfo_value({{player}}.allowed)

Won't be possible, this needs to be done via LuckPerms. As far as I am aware, Placeholder API only supports single arguments, honestly, it would be nice if LP had a placeholder like `%luckperms_check_permission <player> <permission>%`.

**Comment by manashard** [comment]
> Won't be possible, this needs to be done via LuckPerms. As far as I am aware, Placeholder API only supports single arguments, honestly, it would be nice if LP had a placeholder like `%luckperms_check_permission <player> <permission>%`.

No worries. Thanks for adding placeholders, it will help a lot
Cheers
