### ISSUE TITLE
v0.3.0 doesn't seem to register anything

### ISSUE THREAD

**Issue by CodedSakura** [FlashyReese/CommandAliases#5]
Or did the syntax change between subversions?

Environment:
- 1.6.3
- Fabric 0.10.8
- Fabric API 0.25.0
- Command Aliases 0.3.0

Reproduce:
`commandaliases.json`: 
```json
[
    {
        "command": "gm 0",
        "execution": [{"command": "gamemode survival", "type": "CLIENT"}]
    }
]
```
Do `/commandaliases reload`
Do `/gm 0` and receive error:
```
Unknown or incomplete command, see below for error
/gm 0<--[HERE]
```

**Comment by FlashyReese** [comment]
Yes an addition field is now required.
```json
[
    {
        "commandMode": "COMMAND_ALIAS",
        "command": "gm 0",
        "execution": [{"command": "gamemode survival", "type": "CLIENT"}]
    }
]
```
I would recommend giving the wiki a read because of mayor changes.
