### ISSUE TITLE
Could not find existing command

### ISSUE THREAD

**Issue by asundrus** [FlashyReese/CommandAliases#63]
Hi.

I just tested this on one of my servers running the latest Fabric, I tested this command:

`{
    "schemaVersion": 1,
    "commandMode": "COMMAND_REDIRECT_NOARG",
    "command": "survival",
    "redirectTo": "gamemode survival"
}`

It throws this error in the console after Reload:

> [15:42:59] [Server thread/ERROR]: [SERVER] COMMAND_REDIRECT - Could not find existing command "gamemode survival": D:\_server\MC_Fabric\.\config\commandaliases\survival.json

Am I missing something?

**Comment by FlashyReese** [comment]
The `gamemode` command was changed in 1.19.3 internally. You can no longer using redirect for it, but you can achieve the same thing with 
```json
{
  "schemaVersion": 1,
  "command": "survival",
  "commandMode": "COMMAND_CUSTOM",
  "actions": [
    {
      "command": "gamemode survival $executor_name()",
      "commandType": "SERVER"
    }
  ]
}
```

**Comment by asundrus** [comment]
> The `gamemode` command was changed in 1.19.3 internally. You can no longer using redirect for it, but you can achieve the same thing with
> 
> ```json
> {
>   "schemaVersion": 1,
>   "command": "survival",
>   "commandMode": "COMMAND_CUSTOM",
>   "actions": [
>     {
>       "command": "gamemode survival $executor_name()",
>       "commandType": "SERVER"
>     }
>   ]
> }
> ```

I see, thanks, maybe I missed that in the Wiki.
