### ISSUE TITLE
1.21 port ? :) 

### ISSUE THREAD

**Issue by jinkhya** [FlashyReese/CommandAliases#64]
Hello !
Your mod is exactly what I was looking for for our new playthrough on our community servers. I was wondering if you could update it to 1.21. I dunno how much work it is and ofc IRL comes first so if you don't have the time for it at this moment I completely understand. I'm just seeing if you plan on updating it soon - ish :)

Best regards,
Jin

**Comment by FlashyReese** [comment]
It's done :)

**Comment by jinkhya** [comment]
thank you so much !! <3
