### ISSUE TITLE
Strange WARNS appearing in log - "Ambiguity between arguments"

### ISSUE THREAD

**Issue by Abbanon** [FlashyReese/CommandAliases#7]
I'm getting a long string of WARNs in my log from this mod, and they all say something about "Ambiguity between arguments"

Log in question: https://paste.ee/p/D9P8u#s=0&l=359 
(lines **359** to **387**)

Is this something that can be ignored?

**Comment by FlashyReese** [comment]
Can you provide your `commandaliases.json` file?

**Comment by Abbanon** [comment]
Oh wait... I'm *terribly* sorry! This isn't even the right mod repo! 
I got your mod confused with another one that I'm using. Nevermind!
